version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '[%(asctime)s] {%(module)s-%(lineno)d} %(levelname)s %(name)s - %(message)s'

handlers:
  console:
    class: "logging.StreamHandler"
    level: INFO
    formatter: standard
    stream: ext://sys.stderr
  normal_file_handler:
    class: "logging.handlers.TimedRotatingFileHandler"
    level: INFO
    formatter: standard
    filename: './logs/file_log.log'
  file:
    (): custom_logging.hostname_aware_timed_rotating_file_handler.HostnameAwareTimedRotatingFileHandler
    when: midnight
    level: INFO
    formatter: standard
    filename: ./logs/log.logs
#    maxBytes: 10485760
    backupCount: 30
    encoding: utf8
  stream_to_variable:
    (): custom_logging.collated_stream_handler.CollatedStreamHandler
    level: INFO
    formatter: standard

root:
  level: INFO
  handlers: ['console', 'file', 'stream_to_variable']

loggers:
  waitress:
    level: INFO
    handlers: ['console', 'file']
    propagate: no
  wsgi:
    level: INFO
    handlers: ['console', 'file']
    propagate: no
